### ISSUE TITLE
Cannot run TISSUE based on my own dataset

### ISSUE THREAD

**Issue by HelloWorldLTY** [sunericd/TISSUE#2]
Hi, thanks for your work. Following the tutorials you mentioned in the main page, I intend to perform uncertainty quantification for my own dataset. However, although I successfully computed the uncertainty level, I could not set the confidence set. The bug is:

```
ValueError                                Traceback (most recent call last)
Cell In[37], line 1
----> 1 tissue.main.conformalize_prediction_interval (adata, "spage_predicted_expression", calib_genes=adata.var_names,
      2                                               alpha_level=0.23, compute_wasserstein=True)

File /gpfs/gibbs/pi/zhao/tl688/TISSUE/tissue/main.py:917, in conformalize_prediction_interval(adata, predicted, calib_genes, alpha_level, symmetric, return_scores_dict, compute_wasserstein)
    915                     u = G_stdev[(groups==group)&(calib_mask)].flatten() # calibration CCV
    916             # calculate wasserstein distance for the CCV distributions
--> 917             score_dist_wasserstein[groups==group] = wasserstein_distance(u, v).astype(G.dtype)
    919 # add prediction intervals to adata
    920 adata.uns['alpha'] = alpha_level

File /gpfs/gibbs/project/zhao/tl688/conda_envs/scglue_test/lib/python3.8/site-packages/scipy/stats/_stats_py.py:9076, in wasserstein_distance(u_values, v_values, u_weights, v_weights)
   9002 def wasserstein_distance(u_values, v_values, u_weights=None, v_weights=None):
   9003     r"""
   9004     Compute the first Wasserstein distance between two 1D distributions.
   9005 
   (...)
   9074 
   9075     """
-> 9076     return _cdf_distance(1, u_values, v_values, u_weights, v_weights)

File /gpfs/gibbs/project/zhao/tl688/conda_envs/scglue_test/lib/python3.8/site-packages/scipy/stats/_stats_py.py:9209, in _cdf_distance(p, u_values, v_values, u_weights, v_weights)
   9165 def _cdf_distance(p, u_values, v_values, u_weights=None, v_weights=None):
   9166     r"""
   9167     Compute, between two one-dimensional distributions :math:`u` and
   9168     :math:`v`, whose respective CDFs are :math:`U` and :math:`V`, the
   (...)
   9207 
   9208     """
-> 9209     u_values, u_weights = _validate_distribution(u_values, u_weights)
   9210     v_values, v_weights = _validate_distribution(v_values, v_weights)
   9212     u_sorter = np.argsort(u_values)

File /gpfs/gibbs/project/zhao/tl688/conda_envs/scglue_test/lib/python3.8/site-packages/scipy/stats/_stats_py.py:9275, in _validate_distribution(values, weights)
   9273 values = np.asarray(values, dtype=float)
   9274 if len(values) == 0:
-> 9275     raise ValueError("Distribution can't be empty.")
   9277 # Validate the weight array, if specified.
   9278 if weights is not None:

ValueError: Distribution can't be empty.
```

I did get the uncertainty levels based on previous steps:

![image](https://github.com/sunericd/TISSUE/assets/43333475/843f7430-c1b3-4fa6-ac0c-9ef2b78c5279)

Moreover, I wonder if it is possible to extract genes with high certainty for imputation analysis, like what TransImp did:

https://www.biorxiv.org/content/10.1101/2023.01.20.524992v2.full

Thanks a lot.

**Comment by sunericd** [comment]
Thanks for pointing out this issue! A quick fix would be to set `compute_wasserstein=False` since that seems to be where the error is coming from (it won't affect any TISSUE functionality--just won't compute this additional metric).

In the meantime, if you could share a minimum working example (code+data) with me for this bug with the wasserstein distance, that would be very helpful in fixing the issue.

Currently, we only have an approach for cell filtering (see `tissue.downstream.detect_uncertain_cells`). For genes, it is trickier since the prediction interval width will be correlated with the magnitude of the predicted expression. One way to compute the gene ranking is by computing a gene ranking by mean prediction interval width and dividing this ranking by the ranking in mean predicted expression. You could also try dividing the quantities themselves and use that to filter. In terms of pseudocode (haven't tested it myself), this might look something like:

```
# Run tissue.main.conformalize_prediction_interval` before

# get mean prediction interval width
m='spage'
pi_width = adata.obsm[m+f"_predicted_expression_hi"][target_gene].values-adata.obsm[m+f"_predicted_expression_lo"][target_gene].values
mean_pi_width = pi_width.mean(axis=0)

# get mean predicted expression -- you can try a z-score here too like in detect_uncertain_cells
mean_pred_expn = adata.obsm[m+f"_predicted_expression"].mean(axis=0)

# ranking approach (recommended)
uncertainty_score = mean_pi_width.argsort().argsort()/mean_pred_expn.argsort().argsort()

# value approach
uncertainty_score = mean_pi_width/mean_pred_expn
```

I will think about this some more and probably add a gene ranking/filtering function to TISSUE in the future since it might be broadly useful for different analyses.

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your quick responses. I have already set the keyword:

![image](https://github.com/sunericd/TISSUE/assets/43333475/86bf004b-fafe-4992-82a9-ed21eae6f729)


I used the datasets from gimVI's tutorial:

https://docs.scvi-tools.org/en/0.20.3/tutorials/notebooks/gimvi_tutorial.html

For the uncertaity estimation of genes, is it possible to directly use the averaged uncertianty across cells for each gene as ranking metric? Thanks.

**Comment by sunericd** [comment]
Sorry, it should be `compute_wasserstein=False` (I edited in my response above too).

I ran through the main TISSUE functions using the gimvi tutorial datasets that you linked and it runs fine even with `compute_wasserstein=True` (I used SpaGE for imputation/prediction):

```
!pip install --quiet scvi-colab
!pip install --quiet tissue-sc
from scvi_colab import install

install()

import anndata
import matplotlib.pyplot as plt
import numpy as np
import scanpy
from scipy.stats import spearmanr
from scvi.data import cortex, smfish
from scvi.external import GIMVI

import tissue.main, tissue.downstream

spatial_data = smfish()
seq_data = cortex()

# add 'spatial' to obsm keys
spatial_data.obsm['spatial'] = np.vstack((spatial_data.obs.x_coord.values,spatial_data.obs.y_coord.values)).T

# TISSUE
tissue.main.predict_gene_expression (spatial_data, seq_data, ['Tspan12', 'Tshz1', 'Fnbp1l', 'Adamts15', 'Cldn12', 'Rxfp1'],
                                     method="spage", n_folds=10, n_pv=10)

tissue.main.build_spatial_graph(spatial_data, method="fixed_radius", n_neighbors=15)

tissue.main.conformalize_spatial_uncertainty(spatial_data, "spage_predicted_expression", calib_genes=spatial_data.var_names,
                                             grouping_method="kmeans_gene_cell", k=4, k2=2)


tissue.main.conformalize_prediction_interval (spatial_data, "spage_predicted_expression", calib_genes=spatial_data.var_names,
                                              alpha_level=0.23, compute_wasserstein=True)

```
Let me know if you are doing something different and I can check that too.

Yes, the uncertainties could be used as a quick and dirty way to filter genes/cells. I would still divide/normalize the uncertainty by the mean predicted expression since it will scale with the magnitude of expression.

**Comment by HelloWorldLTY** [comment]
Hi, I only analyzed the plp1
```
# hold out target gene
target_gene = "plp1"
target_expn = adata[:, target_gene].X.copy()
adata = adata[:, [gene for gene in gene_names if gene != target_gene]].copy()
```

Does this make the results different? I will try your recommended approach. Thanks.

**Comment by sunericd** [comment]
I just tested using "Plp1" as the only target gene and it should still run without problems. I would also double check that Plp1 is in your RNAseq dataset. Let me know if the problem persists.

**Comment by HelloWorldLTY** [comment]
I see, thanks. I have tested that it worked for me without using computing_wass_distance. 

I think it also could be a problem caused by scipy. Could you please tell me the version of your scipy? Thanks.

**Comment by sunericd** [comment]
The most recent code I tested with scipy == 1.11.4, but these other versions were also used when developing TISSUE (so should probably work too): scipy==1.9.1, 1.9.3, 1.10.1
